import type { calendar_v3 } from 'googleapis';
import { LABELS } from '../../config/labels.config';
import { generateCatalogueKey } from './releaseId';
import { buildEventTimes } from './scheduling';
import type { Release, ScheduledTask } from './types';

/**
 * Note: the `calendar_v3` import above is type-only (see `import type`),
 * so it's erased at compile time and never bundled. That's what makes it
 * safe to import this module from frontend components — the actual
 * googleapis runtime code (and the Node-only modules it pulls in like
 * `fs`/`net`/`child_process`) lives only in calendar.ts, which only the
 * GitHub Actions scripts import.
 */

export function buildEventTitle(release: Release, task: ScheduledTask): string {
  const label = LABELS[release.label];
  return `${label.shortCode} ${release.catalogueNumber} - ${release.artist} - ${task.title} (@${task.owner})`;
}

export function buildEventDescription(release: Release, task: ScheduledTask): string {
  const label = LABELS[release.label];
  const tracklist = release.tracks
    .map((t, i) => {
      const artist = t.artist ? `${t.artist} — ` : '';
      const title = t.remixArtist ? `${t.title} (${t.remixArtist} Remix)` : t.title;
      return `  ${i + 1}. ${artist}${title}`;
    })
    .join('\n');
  return [
    `Label: ${label.name}`,
    `Catalogue: ${release.catalogueNumber}`,
    `Artist: ${release.artist}`,
    `Release title: ${release.releaseTitle}`,
    `Tracklist:`,
    tracklist,
    `Release date: ${release.releaseDateISO}`,
    `Royalty rate: ${release.royaltyRate}`,
    `Royalty notes: ${release.royaltyNotes}`,
    `Genre / style: ${release.genre}`,
    ``,
    `Task: ${task.title}`,
    `Owner: ${task.owner}`,
    `Due: ${task.dueDateISO}`,
    ``,
    `Release ID: ${release.releaseId}`,
    `Generated by Meanwhile Release Scheduler`,
  ].join('\n');
}

export interface ReminderSettings {
  /** Email reminders are off by default — enable per deployment via env var. */
  emailRemindersEnabled: boolean;
}

export function buildReminders(settings: ReminderSettings): calendar_v3.Schema$Event['reminders'] {
  const overrides: calendar_v3.Schema$EventReminder[] = [
    { method: 'popup', minutes: 24 * 60 }, // 1 day before
    { method: 'popup', minutes: 0 }, // at event time
  ];
  if (settings.emailRemindersEnabled) {
    overrides.push({ method: 'email', minutes: 24 * 60 });
  }
  return { useDefault: false, overrides };
}

export function buildEventResource(
  release: Release,
  task: ScheduledTask,
  reminderSettings: ReminderSettings,
  timeZone: string
): calendar_v3.Schema$Event {
  const times = buildEventTimes(task.dueDateISO, timeZone, task.startHour, task.startMinute);
  return {
    summary: buildEventTitle(release, task),
    description: buildEventDescription(release, task),
    start: { dateTime: times.startDateTime, timeZone: times.timeZone },
    end: { dateTime: times.endDateTime, timeZone: times.timeZone },
    reminders: buildReminders(reminderSettings),
    extendedProperties: {
      private: {
        releaseId: release.releaseId,
        catalogueKey: generateCatalogueKey(release),
        taskId: task.id,
      },
    },
  };
}
