#!/bin/zsh
# export-video-assets.sh — Export per-track PNG backgrounds and mark PNG for promo videos
#
# Run AFTER new-release.sh — the TIF must already have the correct artwork and
# track names set. Track names are read directly from the TIF's TRACK_NAMES layer.
#
# Exports to {release folder}/assets/videos/:
#   bg1.png, bg2.png, ...  one per track (mark hidden, single track name)
#   mark.png               the centre mark on a transparent background
#
# Usage:
#   Interactive:     ./scripts/export-video-assets.sh
#   Non-interactive: ./scripts/export-video-assets.sh MW MW090

# ── LABEL CONFIGS ─────────────────────────────────────────────────────────────
LABEL_KEYS=("MW" "MWH")
LABEL_DISPLAY_NAMES=("Meanwhile Recordings" "Meanwhile Horizons")

configure_label() {
  case "$1" in

    MW)
      LABEL_NAME="Meanwhile Recordings"
      TEMPLATE_DIR="/Users/matter/Dropbox/- MEANWHILE/_MW-Template/MW"
      RELEASES_DIR="/Users/matter/Dropbox/- MEANWHILE/Releases - Meanwhile"
      MARK_PSB="MW - mark.psb"
      # Static logo asset — copy meanwhile_RGB_logo_2023-no-border.png into
      # _MW-Template/MW/ to have it picked up automatically, or leave blank.
      LOGO_PNG="${TEMPLATE_DIR}/meanwhile_RGB_logo_2023-no-border.png"
      LAYER_TRACKS="TRACK_NAMES"
      LAYER_MARK="Mark"
      JUST_TRACKS="LEFT"
      ;;

    MWH)
      LABEL_NAME="Meanwhile Horizons"
      TEMPLATE_DIR="/Users/matter/Dropbox/- MEANWHILE/_MW-Template/MWH"
      RELEASES_DIR="/Users/matter/Dropbox/- MEANWHILE/Releases - Horizons"
      MARK_PSB=""
      LOGO_PNG=""
      LAYER_TRACKS="TRACK_NAMES"
      LAYER_MARK="Mark"
      JUST_TRACKS="LEFT"
      ;;

  esac
}

# ─────────────────────────────────────────────────────────────────────────────

print ""
print -P "%F{cyan}%B-- Meanwhile Video Asset Export ──────────────────%b%f"
print ""

# ── MODE: CLI args vs interactive ─────────────────────────────────────────────
if [[ $# -eq 2 ]]; then
  LABEL_KEY="$1"
  CAT_NUMBER="$2"
  configure_label "$LABEL_KEY"
  print -P "  %F{white}$LABEL_NAME%f"
  print ""

elif [[ $# -gt 0 ]]; then
  print -P "%F{red}Usage: ./scripts/export-video-assets.sh [labelKey catNumber]%f"
  print -P "%F{white}Either supply both args or none for interactive mode.%f"
  exit 1

else
  print -P "%F{yellow}Label:%f"
  for i in $(seq 1 ${#LABEL_KEYS[@]}); do
    print -P "  $i.  ${LABEL_DISPLAY_NAMES[$i]}  %F{white}(${LABEL_KEYS[$i]})%f"
  done
  print -Pn "  > "
  read LABEL_CHOICE

  if [[ "$LABEL_CHOICE" =~ ^[0-9]+$ ]] && (( LABEL_CHOICE >= 1 && LABEL_CHOICE <= ${#LABEL_KEYS[@]} )); then
    LABEL_KEY="${LABEL_KEYS[$LABEL_CHOICE]}"
  else
    print -P "%F{red}Invalid choice.%f"; exit 1
  fi

  configure_label "$LABEL_KEY"
  print -P "  %F{white}$LABEL_NAME%f"
  print ""

  print -Pn "%F{yellow}Catalogue number%f  : "
  read CAT_NUMBER
  if [[ -z "$CAT_NUMBER" ]]; then print -P "%F{red}Required.%f"; exit 1; fi
fi

# ── GUARD: unconfigured label ──────────────────────────────────────────────────
if [[ -z "$MARK_PSB" && "$LABEL_KEY" != "MW" ]]; then
  print -P "%F{red}$LABEL_NAME is not fully configured yet.%f"
  print -P "%F{white}Open scripts/export-video-assets.sh and complete the $LABEL_KEY block.%f"
  exit 1
fi

# ── FIND RELEASE FOLDER ───────────────────────────────────────────────────────
EXISTING=("${RELEASES_DIR}"/${CAT_NUMBER}*(N/))

if [[ ${#EXISTING[@]} -eq 1 ]]; then
  RELEASE_DIR="${EXISTING[1]}"
elif [[ ${#EXISTING[@]} -gt 1 ]]; then
  print -P "%F{red}Multiple folders match ${CAT_NUMBER}*:%f"
  for d in "${EXISTING[@]}"; do print -P "  %F{white}${d:t}%f"; done
  print -P "%F{white}Rename or remove duplicates and try again.%f"
  exit 1
else
  print -P "%F{red}No release folder found matching ${CAT_NUMBER}* in:%f"
  print -P "  %F{white}${RELEASES_DIR}%f"
  exit 1
fi

ASSETS_DIR="${RELEASE_DIR}/assets/images"
VIDEOS_DIR="${RELEASE_DIR}/assets/videos"
TIF_PATH="${ASSETS_DIR}/${CAT_NUMBER} - Release Assets.tif"
MARK_PSB_PATH="${TEMPLATE_DIR}/${MARK_PSB}"

if [[ ! -f "$TIF_PATH" ]]; then
  print -P "%F{red}TIF not found: ${TIF_PATH:t}%f"
  print -P "%F{white}Run new-release.sh first to set up the release artwork.%f"
  exit 1
fi

if [[ ! -f "$MARK_PSB_PATH" ]]; then
  print -P "%F{red}Mark PSB not found: ${MARK_PSB_PATH}%f"
  exit 1
fi

print -P "%F{white}Release:%f  ${RELEASE_DIR:t}"
print -P "%F{white}TIF:%f      ${CAT_NUMBER} - Release Assets.tif"
print -P "%F{white}Output:%f   assets/videos/"
print ""

# ── ESCAPE HELPER ─────────────────────────────────────────────────────────────
esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

# ── GENERATE JSX ──────────────────────────────────────────────────────────────
JSX_FILE="/tmp/meanwhile-video-export-${CAT_NUMBER}.jsx"

cat > "$JSX_FILE" << JSXEOF
// Auto-generated by scripts/export-video-assets.sh
var TIF_PATH     = "$(esc "$TIF_PATH")";
var MARK_PSB     = "$(esc "$MARK_PSB_PATH")";
var VIDEOS_DIR   = "$(esc "$VIDEOS_DIR")";
var LAYER_TRACKS = "$(esc "$LAYER_TRACKS")";
var LAYER_MARK   = "$(esc "$LAYER_MARK")";
var JUST_TRACKS  = "$(esc "$JUST_TRACKS")";

function main() {
  var videosFolder = new Folder(VIDEOS_DIR);
  if (!videosFolder.exists) videosFolder.create();

  // ── Open TIF ──────────────────────────────────────────────────────────────
  var tifDoc = open(new File(TIF_PATH));

  var trackLayer = findLayer(tifDoc.layers, LAYER_TRACKS);
  if (!trackLayer) {
    alert("Layer not found: " + LAYER_TRACKS + "\nRun new-release.sh first.");
    tifDoc.close(SaveOptions.DONOTSAVECHANGES);
    return;
  }

  // Read all track names from the text layer (lines separated by \r in PS)
  var rawText   = trackLayer.textItem.contents;
  var rawLines  = rawText.split("\r");
  var tracks    = [];
  for (var i = 0; i < rawLines.length; i++) {
    var t = rawLines[i].replace(/^\s+|\s+$/, "");
    if (t.length > 0) tracks.push(t);
  }

  if (tracks.length === 0) {
    alert("No track names found in " + LAYER_TRACKS + " layer.\nRun new-release.sh first.");
    tifDoc.close(SaveOptions.DONOTSAVECHANGES);
    return;
  }

  // ── Duplicate once and crop to the square artboard ────────────────────────
  // We work on a duplicate so the original TIF is never modified.
  var exportDoc = tifDoc.duplicate("mw_video_export", true);
  cropToSquareArtboard(exportDoc);

  var expTrackLayer = findLayer(exportDoc.layers, LAYER_TRACKS);
  var expMarkLayer  = findLayer(exportDoc.layers, LAYER_MARK);

  // Hide the mark layer for all bg exports
  if (expMarkLayer) expMarkLayer.visible = false;

  // ── bg{n}.png — one per track ──────────────────────────────────────────────
  var justMap = { "LEFT": Justification.LEFT, "RIGHT": Justification.RIGHT, "CENTER": Justification.CENTER };
  for (var n = 0; n < tracks.length; n++) {
    if (expTrackLayer && expTrackLayer.kind === LayerKind.TEXT) {
      expTrackLayer.textItem.contents = tracks[n];
      if (justMap[JUST_TRACKS]) expTrackLayer.textItem.justification = justMap[JUST_TRACKS];
    }
    var outFile = new File(VIDEOS_DIR + "/bg" + (n + 1) + ".png");
    exportPNG(exportDoc, outFile, false);
  }

  exportDoc.close(SaveOptions.DONOTSAVECHANGES);
  tifDoc.close(SaveOptions.DONOTSAVECHANGES);

  // ── mark.png — from the mark PSB with transparency ────────────────────────
  var markDoc = open(new File(MARK_PSB));

  // Hide any solid background layers so the export is transparent
  for (var m = 0; m < markDoc.layers.length; m++) {
    var ml = markDoc.layers[m];
    if (ml.isBackgroundLayer || ml.name.toLowerCase() === "background") {
      try { ml.visible = false; } catch(e) {}
    }
  }

  var markOutFile = new File(VIDEOS_DIR + "/mark.png");
  exportPNG(markDoc, markOutFile, true);
  markDoc.close(SaveOptions.DONOTSAVECHANGES);
}

function exportPNG(doc, outFile, transparency) {
  var opts = new ExportOptionsSaveForWeb();
  opts.format       = SaveDocumentType.PNG;
  opts.PNG8         = false;   // PNG-24
  opts.transparency = transparency;
  doc.exportDocument(outFile, ExportType.SAVEFORWEB, opts);
}

// Crop the document to the bounds of a square top-level LayerSet (artboard).
// If no artboard is found the document canvas is used as-is.
function cropToSquareArtboard(doc) {
  for (var i = 0; i < doc.layers.length; i++) {
    var layer = doc.layers[i];
    if (layer.typename !== "LayerSet") continue;
    var b = layer.bounds; // [left, top, right, bottom] as UnitValues
    var w = b[2].as("px") - b[0].as("px");
    var h = b[3].as("px") - b[1].as("px");
    if (w > 0 && Math.abs(w - h) < 2) {
      doc.crop(b);
      return;
    }
  }
  // No square artboard — use full canvas (assumes TIF canvas is already square)
}

function findLayer(layers, name) {
  for (var i = 0; i < layers.length; i++) {
    if (layers[i].name === name) return layers[i];
    if (layers[i].typename === "LayerSet") {
      var f = findLayer(layers[i].layers, name);
      if (f) return f;
    }
  }
  return null;
}

main();
JSXEOF

# ── RUN IN PHOTOSHOP ──────────────────────────────────────────────────────────
print -P "  %F{cyan}Running in Photoshop — reading tracks from TIF...%f"
print ""

osascript << APPLEEOF > /dev/null
tell application "Adobe Photoshop 2026"
  do javascript of file "${JSX_FILE}"
end tell
APPLEEOF

# ── COPY STATIC LOGO (if available in template folder) ────────────────────────
if [[ -f "$LOGO_PNG" ]]; then
  cp "$LOGO_PNG" "$VIDEOS_DIR/"
  print -P "  %F{green}+%f  videos/$(basename "$LOGO_PNG")"
fi

# ── REPORT ────────────────────────────────────────────────────────────────────
print ""
EXPORTED=("$VIDEOS_DIR"/bg*.png "$VIDEOS_DIR"/mark.png)
FOUND=0
for f in "${EXPORTED[@]}"; do
  if [[ -f "$f" ]]; then
    print -P "  %F{green}✓%f  videos/${f:t}"
    (( FOUND++ ))
  fi
done

if (( FOUND == 0 )); then
  print -P "  %F{red}No PNG files found in assets/videos/ — check for Photoshop errors above.%f"
else
  print ""
  print -P "  %F{white}Done. Drop the mp3 samples into assets/videos/ then open the WFP.%f"
fi
print ""
